import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
const root = join(dirname(fileURLToPath(import.meta.url)), "../investigations/nvidia-rubin");
const read = (file) => JSON.parse(readFileSync(join(root, file), "utf8"));
const nodes = read("nodes.json"); const edges = read("edges.json"); const evidence = read("evidence.json"); const concentration = read("concentration.json"); const intelligence = read("intelligence.json"); const ids = new Set(nodes.nodes.map((node) => node.id)); const evidenceIds = new Set(evidence.evidence.map((item) => item.id)); let pass = true;
function ok(label, condition) { if (!condition) { console.error("FAIL:", label); pass = false; } else console.log("PASS:", label); }
ok("node count in range", nodes.nodes.length >= 15 && nodes.nodes.length <= 30); ok("anchor exists", ids.has(nodes.anchor)); ok("general node types", nodes.nodes.every((node) => ["supplier","component","process","material","infrastructure","product","industry","geography","constraint","other"].includes(node.type)));
edges.edges.forEach((edge, index) => { ok(`${edge.id} sequential`, edge.id === `e${String(index + 1).padStart(2, "0")}`); ok(`${edge.id} endpoints`, ids.has(edge.from) && ids.has(edge.to)); ok(`${edge.id} evidence`, edge.evidence?.length > 0); ok(`${edge.id} class`, ["OBSERVED","INFERRED","ESTIMATED","DISPUTED","UNKNOWN"].includes(edge.class)); edge.evidence.forEach((id) => ok(`${edge.id} evidence ref ${id}`, evidenceIds.has(id))); });
evidence.evidence.forEach((item) => { ok(`${item.id} source`, item.source_url?.startsWith("http") && !!item.publisher); ok(`${item.id} publication metadata`, !!item.source_date && !!item.claim_type && !!item.data_class); });
ok("concentration signals", concentration.signals.length >= 3); ok("modeled intelligence", intelligence.data_class === "MODELED" && intelligence.anchor_id === nodes.anchor); ok("plain-language intelligence", !!intelligence.current_reality && !!intelligence.why_it_matters && !!intelligence.what_changes_from_prior && !!intelligence.what_it_means && !!intelligence.what_could_happen_next); ok("watch signals", intelligence.watch_signals.confirm.length >= 2 && intelligence.watch_signals.invalidate.length >= 2); ok("no numeric reader score", !intelligence.current_reality.includes("confidence")); console.log(`\nRUBIN NODES ${nodes.nodes.length} EDGES ${edges.edges.length} EVIDENCE ${evidence.evidence.length}`); process.exit(pass ? 0 : 1);
