import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

// Static HTML is the production source, not the historical scaffold generator.
// Enumerate tracked pages so private experiments cannot become public routes.
const pages = execFileSync('git', ['ls-files', '*.html'], {encoding:'utf8'}).trim().split('\n');
const routes = new Set();
for (const page of pages) {
  routes.add('/'+page);
  routes.add('/'+page.replace(/\.html$/, ''));
  if (page.endsWith('index.html')) routes.add('/'+page.slice(0,-10));
}
writeFileSync('_headers', '# Generated by scripts/build-headers.mjs\n'+[...routes].sort().map(route => `${route}\n  Content-Type: text/html; charset=utf-8\n`).join('\n'), 'utf8');
console.log(`UTF-8 response headers: ${routes.size} HTML routes`);
